AdvanceUMS/Areas/Admin/Controllers/ActivityLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdvanceUMS.Models;
using AdvanceUMS.Helper;

namespace AdvanceUMS.Areas.Admin.Controllers
{
    public class ActivityLogController : Controller
    {
        AdvanceUMSEntities db = new AdvanceUMSEntities();
        GeneralHelper dHelper = new GeneralHelper();
        // GET: Admin/ActivityLog
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetActivityLog()
        {
            var control = dHelper.GetUserPermission("");
            if (control.IsLogin == false)
                return Redirect("/account/login");
            var activity = dHelper.GetActivityLog(Guid.Empty);
            if (control.IsAdmin == false)
                activity = dHelper.GetActivityLog(new Guid(dHelper.CurrentLoginUser()));            
            return PartialView("_ActivityLog", activity);
        }
    }
}

AdvanceUMS/Areas/Admin/Views/ActivityLog/Index.cshtml
@{
    AdvanceUMS.Helper.GeneralHelper dHelper = new AdvanceUMS.Helper.GeneralHelper();
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Activity Log
        </h1>
        <ol class="breadcrumb">
            <li><a href="/admin/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Activity Log</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    @{ Html.RenderAction("GetActivityLog", "ActivityLog");}
                </div>
            </div>
        </div>
    </section>
</div>